In [1]:
# Import package
%pip install recordlinkage
import recordlinkage

#For this demo let us use the inbuilt dataset from recordlinkage library
#import data set
from recordlinkage.datasets import load_febrl1

#create a dataframe - dfa
dfA = load_febrl1()
dfA.head()

Collecting recordlinkage
  Downloading recordlinkage-0.16-py3-none-any.whl (926 kB)
                                              0.0/926.9 kB ? eta -:--:--
     ---                                      92.2/926.9 kB ? eta -:--:--
     -----                                  122.9/926.9 kB 1.2 MB/s eta 0:00:01
     -------                              194.6/926.9 kB 845.5 kB/s eta 0:00:01
     -------                              204.8/926.9 kB 692.4 kB/s eta 0:00:02
     --------                             225.3/926.9 kB 599.0 kB/s eta 0:00:02
     ---------                            256.0/926.9 kB 525.1 kB/s eta 0:00:02
     -----------                          307.2/926.9 kB 543.9 kB/s eta 0:00:02
     ---------------                      389.1/926.9 kB 577.6 kB/s eta 0:00:01
     ----------------                     419.8/926.9 kB 570.5 kB/s eta 0:00:01
     -------------------                  512.0/926.9 kB 642.5 kB/s eta 0:00:01
     --------------------                 532.5/926.9 kB 608.0 kB/s eta 0:00:01
     -----------------------              593.9/926.9 kB 644.2 kB/s eta 0:00:01
     -------------------------            645.1/926.9 kB 634.9 kB/s eta 0:00:01
     ---------------------------          696.3/926.9 kB 655.9 kB/s eta 0:00:01
     ---------------------------          696.3/926.9 kB 655.9 kB/s eta 0:00:01
     -----------------------------        757.8/926.9 kB 629.8 kB/s eta 0:00:01
     -------------------------------      798.7/926.9 kB 587.1 kB/s eta 0:00:01
     -------------------------------      798.7/926.9 kB 587.1 kB/s eta 0:00:01
     -------------------------------      798.7/926.9 kB 587.1 kB/s eta 0:00:01
     -------------------------------      798.7/926.9 kB 587.1 kB/s eta 0:00:01
     -------------------------------      798.7/926.9 kB 587.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ---------------------------------    860.2/926.9 kB 490.1 kB/s eta 0:00:01
     ----------------------------------   890.9/926.9 kB 350.2 kB/s eta 0:00:01
     ----------------------------------   890.9/926.9 kB 350.2 kB/s eta 0:00:01
     ----------------------------------   890.9/926.9 kB 350.2 kB/s eta 0:00:01
     -----------------------------------  921.6/926.9 kB 331.4 kB/s eta 0:00:01
     ------------------------------------ 926.9/926.9 kB 324.1 kB/s eta 0:00:00
Collecting jellyfish>=1 (from recordlinkage)
  Downloading jellyfish-1.0.3-cp311-none-win_amd64.whl (210 kB)
                                              0.0/210.9 kB ? eta -:--:--
     ------------------                     102.4/210.9 kB 2.0 MB/s eta 0:00:01
     -------------------------------        174.1/210.9 kB 1.3 MB/s eta 0:00:01
     ------------------------------------ 210.9/210.9 kB 988.7 kB/s eta 0:00:00
Requirement already satisfied: numpy>=1.13 in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from recordlinkage) (1.24.3)
Requirement already satisfied: pandas<3,>=1 in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from recordlinkage) (2.0.2)
Requirement already satisfied: scipy>=1 in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from recordlinkage) (1.10.1)
Requirement already satisfied: scikit-learn>=1 in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from recordlinkage) (1.4.2)
Requirement already satisfied: joblib in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from recordlinkage) (1.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas<3,>=1->recordlinkage) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas<3,>=1->recordlinkage) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas<3,>=1->recordlinkage) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn>=1->recordlinkage) (3.4.0)
Requirement already satisfied: six>=1.5 in c:\users\gabriel viceraira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1->recordlinkage) (1.16.0)
Installing collected packages: jellyfish, recordlinkage
Successfully installed jellyfish-1.0.3 recordlinkage-0.16
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: C:\Users\GABRIEL VICERAIRA\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

,given_name,surname,street_number,address_1,address_2,suburb,postcode,state,date_of_birth,soc_sec_id
rec_id,,,,,,,,,,
rec-223-org,NaN,waller,6,tullaroop street,willaroo,st james,4011,wa,19081209,6988048
rec-122-org,lachlan,berry,69,giblin street,killarney,bittern,4814,qld,19990219,7364009
rec-373-org,deakin,sondergeld,48,goldfinch circuit,kooltuo,canterbury,2776,vic,19600210,2635962
rec-10-dup-0,kayla,harrington,NaN,maltby circuit,coaling,coolaroo,3465,nsw,19150612,9004242
rec-227-org,luke,purdon,23,ramsay place,mirani,garbutt,2260,vic,19831024,8099933

In [11]:
indexer = recordlinkage.index.Block(on='given_name')
pairs = indexer.index(dfA)
print (len(pairs))

2082

C:\Users\GABRIEL VICERAIRA\AppData\Local\Temp\ipykernel_23392\1851915744.py:1: DeprecationWarning: The argument 'on' is deprecated. Use 'left_on=...' and 'right_on=None' to simulate the behaviour of 'on'.
  indexer = recordlinkage.index.Block(on='given_name')

In [12]:
# This cell can take some time to compute.
compare_cl = recordlinkage.Compare()
compare_cl.string('given_name', 'given_name',method='jarowinkler', label='given_name')
compare_cl.string('surname', 'surname', method='jarowinkler',label='surname')
compare_cl.exact('date_of_birth', 'date_of_birth', label='date_of_birth')
compare_cl.exact('suburb', 'suburb', label='suburb')
compare_cl.exact('state', 'state', label='state')
compare_cl.string('address_1', 'address_1',method='jarowinkler',label='address_1')
features = compare_cl.compute(pairs, dfA)
features.sample(5)

,,given_name,surname,date_of_birth,suburb,state,address_1
rec_id_1,rec_id_2,,,,,,
rec-337-org,rec-73-org,1.0,0.588624,0,0,0,0.422222
rec-201-org,rec-394-org,1.0,0.455556,0,0,0,0.462626
rec-132-org,rec-359-org,1.0,0.444444,0,0,1,0.524603
rec-51-org,rec-67-dup-0,1.0,0.611111,0,0,0,0.487179
rec-496-dup-0,rec-67-org,1.0,0.000000,0,0,0,0.708314

In [13]:
# select all the features except for given_name since its our blocking key
features1 = features[['suburb','state','surname','date_of_birth','address_1']]
# Unsupervised learning – probabilistic
ecm = recordlinkage.ECMClassifier()
result_ecm = ecm.learn((features1).astype(int),return_type ='series')
result_ecm

C:\Users\GABRIEL VICERAIRA\AppData\Local\Temp\ipykernel_23392\3260253579.py:5: UserWarning: learn is deprecated, ECMClassifier.fit_predict instead
  result_ecm = ecm.learn((features1).astype(int),return_type ='series')

rec_id_1       rec_id_2
rec-183-dup-0  rec-122-org      0
rec-248-org    rec-122-org      0
               rec-183-dup-0    0
rec-122-dup-0  rec-122-org      1
               rec-183-dup-0    0
                               ..
rec-252-org    rec-252-dup-0    1
rec-48-dup-0   rec-48-org       1
rec-298-dup-0  rec-298-org      1
rec-282-org    rec-282-dup-0    1
rec-327-org    rec-411-org      0
Name: classification, Length: 2082, dtype: int32

In [14]:
from recordlinkage.datasets import load_febrl4
dfA, dfB = load_febrl4()
dfA.head()

,given_name,surname,street_number,address_1,address_2,suburb,postcode,state,date_of_birth,soc_sec_id
rec_id,,,,,,,,,,
rec-1070-org,michaela,neumann,8,stanley street,miami,winston hills,4223,nsw,19151111,5304218
rec-1016-org,courtney,painter,12,pinkerton circuit,bega flats,richlands,4560,vic,19161214,4066625
rec-4405-org,charles,green,38,salkauskas crescent,kela,dapto,4566,nsw,19480930,4365168
rec-1288-org,vanessa,parr,905,macquoid place,broadbridge manor,south grafton,2135,sa,19951119,9239102
rec-3585-org,mikayla,malloney,37,randwick road,avalind,hoppers crossing,4552,vic,19860208,7207688

In [15]:
dfB.head()

,given_name,surname,street_number,address_1,address_2,suburb,postcode,state,date_of_birth,soc_sec_id
rec_id,,,,,,,,,,
rec-561-dup-0,elton,NaN,3,light setreet,pinehill,windermere,3212,vic,19651013,1551941
rec-2642-dup-0,mitchell,maxon,47,edkins street,lochaoair,north ryde,3355,nsw,19390212,8859999
rec-608-dup-0,NaN,white,72,lambrigg street,kelgoola,broadbeach waters,3159,vic,19620216,9731855
rec-3239-dup-0,elk i,menzies,1,lyster place,NaN,northwood,2585,vic,19980624,4970481
rec-2886-dup-0,NaN,garanggar,NaN,may maxwell crescent,springettst arcade,forest hill,2342,vic,19921016,1366884

In [17]:
indexer = recordlinkage.index.Block(on='given_name')
pairs = indexer.index(dfA, dfB)

C:\Users\GABRIEL VICERAIRA\AppData\Local\Temp\ipykernel_23392\1409627415.py:1: DeprecationWarning: The argument 'on' is deprecated. Use 'left_on=...' and 'right_on=None' to simulate the behaviour of 'on'.
  indexer = recordlinkage.index.Block(on='given_name')

In [18]:
compare_cl = recordlinkage.Compare()
compare_cl.string('given_name', 'given_name',method='jarowinkler',label='given_name')
compare_cl.string('surname', 'surname', method='jarowinkler',label='surname')
compare_cl.exact('date_of_birth', 'date_of_birth', label='date_of_birth')
compare_cl.exact('suburb', 'suburb', label='suburb')
compare_cl.exact('state', 'state', label='state')
compare_cl.string('address_1', 'address_1',method='jarowinkler',label='address_1')
features = compare_cl.compute(pairs, dfA, dfB)
features.head(10)

                             given_name   surname  date_of_birth  suburb  \
rec_id_1     rec_id_2
rec-1070-org rec-3024-dup-0         1.0  0.436508              0       0
             rec-2371-dup-0         1.0  0.490079              0       0
             rec-4652-dup-0         1.0  0.490079              0       0
             rec-4795-dup-0         1.0  0.000000              0       0
             rec-1314-dup-0         1.0  0.000000              0       0
rec-2371-org rec-3024-dup-0         1.0  0.527778              0       0
             rec-2371-dup-0         1.0  1.000000              1       1
             rec-4652-dup-0         1.0  0.500000              0       0
             rec-4795-dup-0         1.0  0.527778              0       0
             rec-1314-dup-0         1.0  0.527778              0       0

                             state  address_1
rec_id_1     rec_id_2
rec-1070-org rec-3024-dup-0      1   0.000000
             rec-2371-dup-0      0   0.715873
             rec-4652-dup-0      0   0.645604
             rec-4795-dup-0      1   0.552381
             rec-1314-dup-0      1   0.618254
rec-2371-org rec-3024-dup-0      0   0.000000
             rec-2371-dup-0      1   1.000000
             rec-4652-dup-0      1   0.635684
             rec-4795-dup-0      0   0.411111
             rec-1314-dup-0      0   0.672222

In [19]:
# select all the features except for given_name since its our blocking key
features1 = features[['suburb','state','surname','date_of_birth','address_1']]

# unsupervised learning - probablistic
ecm = recordlinkage.ECMClassifier()
result_ecm = ecm.learn((features1).astype(int),return_type ='series')
result_ecm

C:\Users\GABRIEL VICERAIRA\AppData\Local\Temp\ipykernel_23392\2151501193.py:6: UserWarning: learn is deprecated, ECMClassifier.fit_predict instead
  result_ecm = ecm.learn((features1).astype(int),return_type ='series')

rec_id_1      rec_id_2
rec-1070-org  rec-3024-dup-0    0
              rec-2371-dup-0    0
              rec-4652-dup-0    0
              rec-4795-dup-0    0
              rec-1314-dup-0    0
                               ..
rec-4528-org  rec-4528-dup-0    1
rec-4887-org  rec-4887-dup-0    1
rec-4350-org  rec-4350-dup-0    1
rec-4569-org  rec-4569-dup-0    1
rec-3125-org  rec-3125-dup-0    1
Name: classification, Length: 77249, dtype: int32